// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;

      /*  throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); */
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyiVGZJvrGJubP7L4UErvp4tFykPhPCmM',
    appId: '1:519511846544:web:4f7a89bea7d05ad8e0b215',
    messagingSenderId: '519511846544',
    projectId: 'rider-9b757',
    authDomain: 'rider-9b757.firebaseapp.com',
    storageBucket: 'rider-9b757.firebasestorage.app',
    measurementId: 'G-S1PMHZW0ZF',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCyiVGZJvrGJubP7L4UErvp4tFykPhPCmM',
    appId: '1:519511846544:web:4f7a89bea7d05ad8e0b215',
    messagingSenderId: '519511846544',
    projectId: 'rider-9b757',
    authDomain: 'rider-9b757.firebaseapp.com',
    storageBucket: 'rider-9b757.firebasestorage.app',
    measurementId: 'G-S1PMHZW0ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlRWOem239iDLkMxO5uLfBolb7FKcAQo',
    appId: '1:519511846544:android:49413420e7f0c04ee0b215',
    messagingSenderId: '519511846544',
    projectId: 'rider-9b757',
    storageBucket: 'rider-9b757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKl3xx7un61MFTInagzuPa45V00BGpF4',
    appId: '1:519511846544:ios:c1e20ac68f5a9131e0b215',
    messagingSenderId: '519511846544',
    projectId: 'rider-9b757',
    storageBucket: 'rider-9b757.firebasestorage.app',
    iosClientId:
        '519511846544-d77u7kafg6qoc1kacq1mes8bpj3faci7.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnKl3xx7un61MFTInagzuPa45V00BGpF4',
    appId: '1:519511846544:ios:c1e20ac68f5a9131e0b215',
    messagingSenderId: '519511846544',
    projectId: 'rider-9b757',
    storageBucket: 'rider-9b757.firebasestorage.app',
    iosClientId:
        '519511846544-d77u7kafg6qoc1kacq1mes8bpj3faci7.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyiVGZJvrGJubP7L4UErvp4tFykPhPCmM',
    appId: '1:519511846544:web:0ed3966a124354fde0b215',
    messagingSenderId: '519511846544',
    projectId: 'rider-9b757',
    authDomain: 'rider-9b757.firebaseapp.com',
    storageBucket: 'rider-9b757.firebasestorage.app',
    measurementId: 'G-Q09W8J81P2',
  );
}
